<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>

    <parent>
        <groupId>com.antwerkz</groupId>
        <artifactId>antwerkz-parent</artifactId>
        <version>73</version>
    </parent>

    <artifactId>cartographer</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <kotlin.version>2.4.10</kotlin.version>
        <dokka.version>2.2.0</dokka.version>
        <kotlin.compiler.jvmTarget>17</kotlin.compiler.jvmTarget>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <bytebuddy.version>1.18.11</bytebuddy.version>
        <junit.version>6.1.3</junit.version>
        <opentelemetry.version>1.65.0</opentelemetry.version>
        <maven.version>4.0.0-rc-5</maven.version>
    </properties>

    <scm>
        <connection>scm:git:git@github.com:evanchooly/cartographer.git</connection>
        <developerConnection>scm:git:git@github.com:evanchooly/cartographer.git</developerConnection>
        <url>https://github.com/evanchooly/cartographer</url>
    </scm>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.opentelemetry</groupId>
                <artifactId>opentelemetry-bom</artifactId>
                <version>${opentelemetry.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>net.bytebuddy</groupId>
                <artifactId>byte-buddy</artifactId>
                <version>${bytebuddy.version}</version>
            </dependency>
            <dependency>
                <groupId>net.bytebuddy</groupId>
                <artifactId>byte-buddy-agent</artifactId>
                <version>${bytebuddy.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib</artifactId>
                <version>${kotlin.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-test-junit5</artifactId>
                <version>${kotlin.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <subprojects>
        <subproject>cartographer-agent</subproject>
        <subproject>cartographer-maven-plugin</subproject>
    </subprojects>

</project>
