name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: 17
